def monthly_interest():
    annual_intrest = eval(input("What is your annual interest rate?"))
    billing_cycle = eval(input("what is the number of days in the billing cycle?"))
    previous_net_balance = eval(input("what is your previous net balance?"))
    payment_amount = eval(input("what is your payment amount?"))
    day_for_billing_cycle = eval(input("what is the day the billing cycle payment was made? "))
    step_one = (previous_net_balance * 31)
    days_before_cycle_ends = (billing_cycle - day_for_billing_cycle)
    specific_day_payment = (payment_amount * days_before_cycle_ends)
    step_three = (step_one - specific_day_payment)
    average_daily_balance = (step_three / billing_cycle)
    monthly_interest = (annual_intrest / 12)
    interest_monthly_percentage = (monthly_interest / 100)
    print("Your monthly interest charge is:", average_daily_balance * interest_monthly_percentage)
